### ISSUE TITLE
How get normal image?

### ISSUE THREAD

**Issue by witchfindertr** [batdan/midjourney-php#7]
$imgUrl  = $message->upscaled_photo_url;

$imgUrl  = $message->photo_url; 

??? how

**Comment by batdan** [comment]
```php
$midjourney = new MidjourneyImageCreator($discordChannelId, $discordUserToken);

// Example of a prompt: text is separated from tags
$promptText = "aerial view of a giant fish tank shaped like a tower in the middle of new york city, https://depuismonhamac.jardiland.com/wp-content/uploads/2019/06/AdobeStock_196378179.jpeg";
$promptTags = "8k octane render, photorealistic --ar 9:20 --v 5";

$message = $midjourney->imageCreationV2($promptText, $promptTags);
$imgUrl  = $message->upscaled_photo_url;
```

**Comment by witchfindertr** [comment]
> ```
> $midjourney = new MidjourneyImageCreator($discordChannelId, $discordUserToken);
> 
> // Example of a prompt: text is separated from tags
> $promptText = "aerial view of a giant fish tank shaped like a tower in the middle of new york city, https://depuismonhamac.jardiland.com/wp-content/uploads/2019/06/AdobeStock_196378179.jpeg";
> $promptTags = "8k octane render, photorealistic --ar 9:20 --v 5";
> 
> $message = $midjourney->imageCreationV2($promptText, $promptTags);
> $imgUrl  = $message->upscaled_photo_url;
> ```

this is 1 image ,how do we get 4 of them ?

**Comment by batdan** [comment]
This is not planned at the moment.
My goal was to be able to generate an image without human intervention. This would be technically doable, but not without modifying the main class.
